//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_ChallengeTable
    {
        public int ChallengeId { get; set; }
        public string ChallengerId { get; set; }
        public string ChallengedId { get; set; }
        public Nullable<bool> ChallengedAccepted { get; set; }
        public Nullable<int> ChallengerValue { get; set; }
        public Nullable<int> ChallengedValue { get; set; }
        public int ExerciseId { get; set; }
        public int ChallengeGoal { get; set; }
        public System.DateTime ChallengeStart { get; set; }
        public System.DateTime ChallengeEnd { get; set; }
        public int ChallengeScore { get; set; }
        public string ChallengeTitle { get; set; }
    }
}
