//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_UserSettings
    {
        public string UserId { get; set; }
        public string UserEmail { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserGender { get; set; }
        public string FacebookToken { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string FacebookId { get; set; }
    }
}
