//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_UserLog
    {
        public string UserId { get; set; }
        public System.DateTime LoggedIn { get; set; }
        public int id { get; set; }
    }
}
