//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_UserExercise
    {
        public string UserId { get; set; }
        public int ExerciseId { get; set; }
        public int ExerciseValue { get; set; }
        public int ExerciseValue1 { get; set; }
        public int ExerciseValue2 { get; set; }
        public int ExerciseValue3 { get; set; }
        public int ExerciseMultiplier { get; set; }
        public int ExerciseScore { get; set; }
        public System.DateTime ExerciseDate { get; set; }
        public int UserExerciseId { get; set; }
    }
}
